name: hyva-stage-deploy

on:
  workflow_dispatch:

jobs:
  deployment-job:
      name: Hyva Stage Deploy
      runs-on: ubuntu-latest
      steps:
        - name: SSH into the machine and run some commands
          uses: appleboy/ssh-action@master
          with:
            host: 44.214.224.241
            username: sigodev
            key:  ${{ secrets.SH_SSH }}
            port: 22
            script: |
              cd htdocs/dev-sigosigns.humdash.com/cap
              echo "Running deployment script on the server"
              whoami
              pwd
              cap --version
