name: hyva-stage-deploy

on:
  workflow_dispatch:

jobs:
  deployment-job:
      name: Hyva Stage Deploy
      runs-on: ubuntu-latest
      steps:
        - name: SSH into the machine and run some commands
          uses: appleboy/ssh-action@master
          with:
            host: 157.241.9.42
            username: couture
            key:  ${{ secrets.SH_SSH }}
            port: 22
            envs: |
              PATH=/home/couture/.rbenv/shims/cap:$PATH
            script: |
              cd capistrano
              echo "Running deployment script on the server"
              whoami
              pwd
              cap --version
