name: deployment

on:
  workflow_dispatch:

jobs:
  deployment-job:
      name: Deployment
      runs-on: ubuntu-latest
      steps:
        - name: SSH into the machine and run some commands
          uses: appleboy/ssh-action@master
          with:
            host: 15.207.108.125
            username: build
            key:  ${{ secrets.SH_SSH }}
            port: 22
            script: |
              export PATH="$HOME/.rbenv/bin:$PATH"
              eval "$(rbenv init -)"
              rbenv global 3.2.2
              ./deployment.sh
              cd capistrano
              echo "Running deployment script on the server"
              whoami
              pwd
              cap develop deploy
