name: deployment

on:
  workflow_dispatch:

jobs:
  deployment-job:
      name: Deployment
      runs-on: ubuntu-latest
      steps:
        - name: SSH into the machine and run some commands
          uses: appleboy/ssh-action@master
          with:
            host: 3.221.225.1
            username: bannershop
            key: ${{ secrets.SH_SSH_BLD }}
            port: 22
            script: |
              export PATH="$HOME/.rbenv/bin:$PATH"
              eval "$(rbenv init -)"
              rbenv global 3.2.2
              cd /home/bannershop/build/bannershopau
              echo "Running deployment script on the server"
              cap develop deploy
