name: http_status

on:
  workflow_dispatch:


jobs:
  status_job:
      name: Status
      runs-on: ubuntu-latest
      steps:
        - name: Make Request
          id: myRequest
          uses: fjogeleit/http-request-action@v1
          with:
            url: "https://cic-deploy.humdash.com/"
        - name: Show Response
          if: contains(steps.myRequest.outputs.response, 'Copyright © 2020 Cicero Mfg.') == false
          uses: appleboy/ssh-action@master
          with:
            host: 35.164.77.158
            username: runcloud
            key:  ${{ secrets.SH_SSH }}
            port: 22
            script: |
              cd /home/runcloud/webapps/cic_test/tools/cap
              echo "Running deployment script on the server"
              cap local deploy
