name: hyva-stage-deploy-test

on:
  workflow_dispatch:
    inputs:
      current-branch:
        description: "Please give a custom branch to deploy"
        required: false
        default: ''
  
  pull_request:
    branches:
      - hyva-stage
    types:
      - closed

jobs:
  deployment-job:
      name: Hyva Stage Deploy
      if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
      runs-on: ubuntu-latest
      
      steps:
        - name: SSH into the machine and run some commands
          uses: appleboy/ssh-action@master
          with:
            host: 3.221.225.1
            username: sigosigns
            key:  ${{ secrets.SH_SSH_BLD }}
            port: 22
            script: |
              export PATH="$HOME/.rbenv/bin:$PATH"
              eval "$(rbenv init -)"
              rbenv global 3.2.2
              cd /home/sigosigns/build/capistrano
              echo "Running deployment script on the server with " ${{ github.event.inputs.current-branch }}
              CUSTOM_BRANCH=${{ github.event.inputs.current-branch }} nohup cap staging deploy > cap_deploy.log 2>&1 &
