name: install magento2

on:
  workflow_dispatch:


jobs:
  static:
    name: install
    runs-on: ubuntu-latest

    services:
      magento2:
        image: phoenixmedia/magento2:2.4.5
        options: --name magento2
        volumes:
        - ${{ github.workspace }}:/app

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: creating composer
        run: docker exec magento2 ls  app/

      - name: creating composer2
        run: docker exec magento2 ls  /app/

      # - name: adding auth json
      #   run: docker cp . magento2:/app/code/

      # - name: install moonsoon
      #   run: docker exec magento2 ls /app/

      # - name: install moonsoonsdf
      #   run: docker exec magento2 ls /app/code

    
