name: install magento2

on:
  workflow_dispatch:


jobs:

  services:
    magento2:
        image: phoenixmedia/magento2:2.4.5
        options: --name magento2

  static:
    name: M2 Coding Standard
    runs-on: ubuntu-latest
    
    - name: creating composer
      run: docker exec magento2 mkdir /root/.composer

    - name: adding auth json
      run: docker cp auth.json.sample magento2:/root/.composer/auth.json

    - name: install moonsoon
      run: docker exec magento2 composer require monsoonconsulting/magento2-pwa
