name: run tests

on:
  workflow_dispatch:

jobs:
  static:
    name: M2 Coding Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - run: |
          MAGENTO_DIRECTORY="magento"
          echo "MAGENTO_DIRECTORY=$MAGENTO_DIRECTORY" >> $GITHUB_OUTPUT
        id: setup-magento-compute-directory
        shell: bash

      - run: | 
          mkdir -p ${{ steps.setup-magento-compute-directory.outputs.MAGENTO_DIRECTORY }}
        name: Make a directory that may not exist.
        shell: bash

      - run: composer create-project --repository-url="https://mirror.mage-os.org/" "~2.4.5" ${{ steps.setup-magento-compute-directory.outputs.MAGENTO_DIRECTORY }} --no-install
        working-directory: magento
        shell: bash
        name: Create Magento Project