name: run tests

on:
  workflow_dispatch:

jobs:
  static:
    name: M2 Coding Standard
    runs-on: ubuntu-latest
    services:
      mysql:
        image: docker://mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: docker://elasticsearch:7.17.0
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health"  --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - uses: actions/checkout@v3
      - name: 'install fresh magento repo'
        uses: MAD-I-T/magento-actions@v3.21
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'install-magento'
          magento_version: 2.4.3
          no_push: 1

      - run: php7.4 bin/magento sample:data:deploy
        working-directory: magento