name: run tests

on:
  workflow_dispatch:

jobs:
  static:
    name: M2 Coding Standard
    runs-on: ubuntu-latest

    container: ubuntu
    services:
      container_name:
        image: phoenixmedia/magento2:2.4.5
    

    steps:
      - run: docker exec container_name ls -lah