name: run tests

on:
  workflow_dispatch:

jobs:
  static:
    name: M2 Coding Standard
    runs-on: ubuntu-latest
    services:
      mysql:
        image: docker://mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: docker://elasticsearch:7.17.0
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health"  --health-interval=10s --health-timeout=5s --health-retries=10

    container:
      image: phoenixmedia/magento2:2.4.5
    steps:
      - name: log ls
        run: |
          cd ..
          ls -lah