name: m2-actions-test

on:
  workflow_dispatch:

jobs:
  magento2-build:
    runs-on: ubuntu-latest
    name: 'm2 tests & build'      
    steps:
    - uses: actions/checkout@v3
    - name: 'install fresh magento repo'
      if: ${{true}}
      uses: MAD-I-T/magento-actions@v3.20
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        process: 'install-magento'
        magento_version: 2.4.3
      
    - name: phpsniffer
      uses: tinovyatkin/action-php-codesniffer@v1
      with:
          files: "**"
          scope: files
          phpcs_path: vendor/bin/phpcs
          standard: vendor/magento/magento-coding-standard/Magento2/ruleset.xml